#!/bin/bash

dir="$(dirname "$0")"

. $dir/function/check
source $dir/function/server
source $dir/function/cleanup
source $dir/function/actions/user


function server {
    eval `resize`
    SERVER=$(whiptail \
        --notags \
        --title "Server Installation" \
        --menu "\nWhat third-party software would you like to install?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        cleanall             'Basic Cleaning Service' \
        user                'Create a New User'\
        3>&1 1>&2 2>&3)
     
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $SERVER
    else
        clear && main
    fi
}
