#!/bin/bash


dir="$(dirname "$0")"

. $dir/function/function/cleanup
. $dir/function/function/server_setup

function server {
    eval `resize`
    SERVER=$(whiptail \
        --notags \
        --title "Server Installation" \
        --menu "\nWhat third-party software would you like to install?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        'server_setup'            'Basic Server Setup' \
        'cleanup'             'Basic Cleaning Service' \
        3>&1 1>&2 2>&3)
     
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        clear && $SERVER
    else
        clear && main
    fi
}
